--Create db
USE [master]
GO

/****** Object:  Database [ServerTrack]    Script Date: 11/28/2016 10:20:47 ******/
CREATE DATABASE [ServerTrack] ON  PRIMARY
( NAME = N'ServerPerf', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\ServerPerf.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'ServerPerf_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\ServerPerf_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ServerTrack] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServerTrack].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ServerTrack] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [ServerTrack] SET ANSI_NULLS OFF
GO

ALTER DATABASE [ServerTrack] SET ANSI_PADDING OFF
GO

ALTER DATABASE [ServerTrack] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [ServerTrack] SET ARITHABORT OFF
GO

ALTER DATABASE [ServerTrack] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [ServerTrack] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [ServerTrack] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [ServerTrack] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [ServerTrack] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [ServerTrack] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [ServerTrack] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [ServerTrack] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [ServerTrack] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [ServerTrack] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [ServerTrack] SET  DISABLE_BROKER
GO

ALTER DATABASE [ServerTrack] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [ServerTrack] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [ServerTrack] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [ServerTrack] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [ServerTrack] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [ServerTrack] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [ServerTrack] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [ServerTrack] SET  READ_WRITE
GO

ALTER DATABASE [ServerTrack] SET RECOVERY FULL
GO

ALTER DATABASE [ServerTrack] SET  MULTI_USER
GO

ALTER DATABASE [ServerTrack] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [ServerTrack] SET DB_CHAINING OFF
GO

---Create Table
USE [ServerTrack]
GO

/****** Object:  Table [dbo].[PerfCounters]    Script Date: 11/26/2016 8:47:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PerfCounters](
	[ComputerName] [nchar](50) NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL DEFAULT GETDATE(),
	[Cpu_Usage] [float] NOT NULL,
	[Ram_Usage] [float] NOT NULL
)

GO